return {
  {import ="plugins.http-rest-client.rest-nvim"},
  --{import ="plugins.http-rest-client.resty"}

  -- ---@type LazyPlugin
  -- {
  --   "rest-nvim/rest.nvim",
  --   enabled = false,
  --   ft = "http",
  --   lazy = true,
  --   --tag = 'v2.0.1',
  --   --ft = "http",
  --   dependencies = {
  --     "vhyrro/luarocks.nvim",
  --   },
  --   config = function()
  --     require("rest-nvim").setup()
  --   end,
  -- }

  --{
  --  "rest-nvim/rest.nvim", -- also see https://github.com/BlackLight/nvim-http (python-based)
  --  enabled = true,
  --  dependencies = { "nvim-lua/plenary.nvim" },
  --  config = function()
  --    require("rest-nvim").setup({
  --      ---- Open request results in a horizontal split
  --      --result_split_horizontal = false,
  --      ---- Keep the http file buffer above|left when split horizontal|vertical
  --      --result_split_in_place = false,
  --      ---- Skip SSL verification, useful for unknown certificates
  --      --skip_ssl_verification = false,
  --      ---- Encode URL before making request
  --      --encode_url = true,
  --      ---- Highlight request on run
  --      --highlight = {
  --      --  enabled = true,
  --      --  timeout = 150,
  --      --},
  --      --result = {
  --      --  -- toggle showing URL, HTTP info, headers at top the of result window
  --      --  show_url = true,
  --      --  show_http_info = true,
  --      --  show_headers = true,
  --      --  -- executables or functions for formatting response body [optional]
  --      --  -- set them to false if you want to disable them
  --      --  formatters = {
  --      --    json = "jq",
  --      --    html = function(body)
  --      --      return vim.fn.system({ "tidy", "-i", "-q", "-" }, body)
  --      --    end,
  --      --  },
  --      --},
  --      ---- Jump to request line on run
  --      --jump_to_request = false,
  --      --env_file = ".env",
  --      --custom_dynamic_variables = {},
  --      --yank_dry_run = true,
  --    })
  --  end,
  --},
  ---@type LazyPlugin
  --{
  --  "BlackLight/nvim-http",
  --  enabled = false,
  --  build = {
  --    -- Ensure we are in a venv context, if so, install required packages
  --    "python -c 'import sys; exit(0) if sys.prefix != sys.base_prefix else exit(1)' && pip install pyvim requests neovim || exit 1",
  --  },
  --  lazy = false,
  --  --config = function()
  --  --  vim.cmd('command! -nargs=0 -range Http call http#Run()')
  --  --  vim.cmd('command! -nargs=0 HttpStop call http#Stop()')
  --  --end
  --},
}
