#!/usr/bin/env python3

import os
import subprocess
import sys
from simple_term_menu import TerminalMenu

def log(message, level="INFO"):
    # ANSI escape sequences for colored output
    levels = {
        "DEBUG": "\033[34m",    # Blue
        "INFO": "\033[32m",     # Green
        "WARNING": "\033[33m",  # Yellow
        "ERROR": "\033[31m",    # Red
        "CRITICAL": "\033[35m", # Magenta
        "RESET": "\033[0m"      # Reset
    }
    color_code = levels.get(level, levels["RESET"])
    print(f"{color_code}[{level}] {message}{levels['RESET']}")

def is_executable(file_path):
    # On Windows, check if the file exists
    # On Unix-like systems, check if the file is executable
    return os.path.isfile(file_path) and (os.name == 'nt' or os.access(file_path, os.X_OK))

def read_single_line(file_path):
    with open(file_path, 'r') as file:
        line = file.readline().strip()
    return line

def get_parent_directory(path):
    return os.path.abspath(os.path.join(path, os.pardir))

def main():
    worktree_dir = subprocess.check_output(['git', 'rev-parse', '--show-toplevel']).strip().decode()
    branches_dir = get_parent_directory(worktree_dir)
    repo_dir = get_parent_directory(branches_dir)
    hooks_dir = os.path.join(repo_dir, '.git', 'hooks')

    # This works because the list of refs being pushed is passed on standard input
    if 'null' in sys.stdin.read():
        log("You really do not want to push this branch. Aborting.", "ERROR")
        sys.exit(1)

    def ask_to_run_from_user():
      print("Shall I run the local pre-push hook?")
      terminal_menu = TerminalMenu(["Yes", "No"])
      idx = terminal_menu.show()
      return idx
      
    should_run = ask_to_run_from_user()
    if should_run == 1:
      log("Skipping local pre-push script. Exiting.")
      sys.exit(0)
    # Prompt the user to ask if the precheck script should be run
    # try:
    #   run_precheck = input("Do you want to run the pre-push script? (yes/no): ").strip().lower()
    #   if not run_precheck.startswith('y'):
    #       log("Precheck script not run. Exiting.")
    #       sys.exit(0)
    # except EOFError:
    #   log("No input provided. Continuing to avoid error")

    # Check if the hook exists in the worktree hooks directory
    pre_push_hook = os.path.join(hooks_dir, 'pre-push')
    if is_executable(pre_push_hook):
        log(f"Found {pre_push_hook}. Executing.")
        # Execute the worktree hook
        # os.execv(pre_push_hook, [pre_push_hook] + sys.argv[1:])
        # Execute the worktree hook
        result = subprocess.run([pre_push_hook] + sys.argv[1:], env=os.environ)
        if result.returncode != 0:
            log("Pre-push hook failed.", "ERROR")
            sys.exit(result.returncode)
    else:
        # Execute the global hook
        log(f"Completed pre-push. No hook under {pre_push_hook} found. Exiting.")

if __name__ == "__main__":
    main()
